# Copyright 2022 Heath Stewart.
# Licensed under the MIT License. See LICENSE.txt in the project root for license information.

name: ci
on:
  pull_request:
  workflow_call:

defaults:
  run:
    shell: bash

env:
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: -Dwarnings

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependencies
      run: npm ci
    - name: Set up toolchain
      run: rustup show
    - name: Check formatting
      if: success() && github.event_name != 'workflow_call'
      run: cargo fmt --all -- --check
    - name: Test
      run: cargo test --all
    - name: Lint
      run: cargo clippy --no-deps
    - name: Install tools
      run: cargo install wasm-pack
    - name: Pack
      run: npm run package
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: ./dist
